
// This file has been generated by the metapod robotbuilder library.
#ifndef HRP4G2_CONFIG_HH
# define HRP4G2_CONFIG_HH

// Handle portable symbol export.
// Defining manually which symbol should be exported is required
// under Windows whether MinGW or MSVC is used.
//
// The headers then have to be able to work in two different modes:
// - dllexport when one is building the library,
// - dllimport for clients using the library.
//
// On Linux, set the visibility accordingly. If C++ symbol visibility
// is handled by the compiler, see: http://gcc.gnu.org/wiki/Visibility
# if defined _WIN32 || defined __CYGWIN__
// On Microsoft Windows, use dllimport and dllexport to tag symbols.
#  define HRP4G2_DLLIMPORT __declspec(dllimport)
#  define HRP4G2_DLLEXPORT __declspec(dllexport)
#  define HRP4G2_DLLLOCAL
# else
// On Linux, for GCC >= 4, tag symbols using GCC extension.
#  if __GNUC__ >= 4
#   define HRP4G2_DLLIMPORT __attribute__ ((visibility("default")))
#   define HRP4G2_DLLEXPORT __attribute__ ((visibility("default")))
#   define HRP4G2_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
// Otherwise (GCC < 4 or another compiler is used), export everything.
#   define HRP4G2_DLLIMPORT
#   define HRP4G2_DLLEXPORT
#   define HRP4G2_DLLLOCAL
#  endif // __GNUC__ >= 4
# endif // defined _WIN32 || defined __CYGWIN__

# ifdef HRP4G2_STATIC
// If one is using the library statically, get rid of
// extra information.
#  define HRP4G2_DLLAPI
#  define HRP4G2_LOCAL
# else
// Depending on whether one is building or using the
// library define DLLAPI to import or export.
#  ifdef hrp4g2_EXPORTS
#   define HRP4G2_DLLAPI HRP4G2_DLLEXPORT
#  else
#   define HRP4G2_DLLAPI HRP4G2_DLLIMPORT
#  endif // HRP4G2_EXPORTS
#  define HRP4G2_LOCAL HRP4G2_DLLLOCAL
# endif // HRP4G2_STATIC
#endif //! HRP4G2_CONFIG_HH

