roboptim::retargeting::AnimatedInteractionMesh Class Reference
roboptim::retargeting::AnimatedInteractionMesh Class Reference
Stores a set of interaction mesh representing a motion.
#include <roboptim/retargeting/animated-interaction-mesh.hh>
Public Types
typedef boost::adjacency_list
< boost::vecS, boost::vecS,
boost::undirectedS, Vertex,
Edge > graph_t
Graph used to store the robots segments.
typedef boost::graph_traits
< graph_t >::vertex_iterator vertex_iterator_t
typedef boost::graph_traits
< graph_t >::edge_iterator edge_iterator_t
typedef boost::graph_traits
< graph_t >::out_edge_iterator out_edge_iterator_t
typedef boost::graph_traits
< graph_t >::edge_descriptor edge_descriptor_t
typedef boost::graph_traits
< graph_t >::vertex_descriptor vertex_descriptor_t
typedef boost::property_map
< graph_t,
boost::vertex_index_t >::type index_map_t
typedef boost::graph_traits
< graph_t >
::adjacency_iterator adjacency_iterator_t
typedef boost::adjacency_list
< boost::vecS, boost::vecS,
boost::undirectedS,
InteractionMeshVertex,
InteractionMeshEdge > interaction_mesh_graph_t
Graph used to represent the interaction mesh.
typedef boost::graph_traits
< interaction_mesh_graph_t >
::vertex_iterator interaction_mesh_vertex_iterator_t
typedef boost::graph_traits
< interaction_mesh_graph_t >
::edge_iterator interaction_mesh_edge_iterator_t
typedef boost::graph_traits
< interaction_mesh_graph_t >
::out_edge_iterator interaction_mesh_out_edge_iterator_t
typedef boost::graph_traits
< interaction_mesh_graph_t >
::edge_descriptor interaction_mesh_edge_descriptor_t
typedef boost::graph_traits
< interaction_mesh_graph_t >
::vertex_descriptor interaction_mesh_vertex_descriptor_t
typedef boost::property_map
< interaction_mesh_graph_t,
boost::vertex_index_t >::type interaction_mesh_index_map_t
typedef boost::graph_traits
< interaction_mesh_graph_t >
::adjacency_iterator interaction_mesh_adjacency_iterator_t
Public Member Functions
AnimatedInteractionMesh ()
~AnimatedInteractionMesh ()
const double & framerate () const
unsigned numFrames () const
unsigned numVertices () const
std::size_t optimizationVectorSize () const
std::size_t optimizationVectorSizeOneFrame () const
const graph_t & graph () const
graph_t & graph ()
const Eigen::VectorXd & makeOptimizationVector () const
Eigen::VectorBlock< const
Eigen::VectorXd,
Eigen::Dynamic > makeOptimizationVectorOneFrame (unsigned frameId) const
Eigen::VectorXd & state ()
Access the interal vector directly.
const Eigen::VectorXd & state () const
void writeGraphvizGraphs (std::ostream &out, unsigned id)
void writeGraphvizInteractionMeshGraphs (std::ostream &out, unsigned id)
void writeGraphvizGraphs (const std::string &path)
void writeTrajectory (const std::string &filename)
void computeVertexWeights ()
Compute current edges weights based on vertices positions.
void recomputeCachedData ()
Recompute cached data using graph.
const std::vector
< interaction_mesh_graph_t > & interactionMeshes () const
std::vector
< interaction_mesh_graph_t > & interactionMeshes ()
void computeInteractionMeshes ()
void computeInteractionMesh (unsigned frameId)
vertex_iterator_t getVertexFromLabel (const std::string &label) const
vertex_iterator_t getVertexFromPosition (unsigned frameId, double x, double y, double z) const
Static Public Member Functions
static
AnimatedInteractionMeshShPtr_t loadAnimatedMesh (cnoid::MarkerMotionPtr markerMotion, cnoid::CharacterPtr character)
static
AnimatedInteractionMeshShPtr_t makeFromOptimizationVariables (const Eigen::Matrix< double, Eigen::Dynamic, 1 > &x, AnimatedInteractionMeshShPtr_t previousAnimatedMesh)
Static Protected Member Functions
static void loadEdgesFromYaml (const YAML::Node &node, AnimatedInteractionMeshShPtr_t animatedMesh)
Detailed Description
Stores a set of interaction mesh representing a motion.
Member Typedef Documentation
typedef boost::graph_traits<graph_t>::adjacency_iterator roboptim::retargeting::AnimatedInteractionMesh::adjacency_iterator_t
typedef boost::graph_traits<graph_t>::edge_descriptor roboptim::retargeting::AnimatedInteractionMesh::edge_descriptor_t
typedef boost::graph_traits<graph_t>::edge_iterator roboptim::retargeting::AnimatedInteractionMesh::edge_iterator_t
typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::undirectedS, Vertex, Edge> roboptim::retargeting::AnimatedInteractionMesh::graph_t
Graph used to store the robots segments.
typedef boost::property_map<graph_t, boost::vertex_index_t>::type roboptim::retargeting::AnimatedInteractionMesh::index_map_t
typedef boost::graph_traits< interaction_mesh_graph_t>::adjacency_iterator roboptim::retargeting::AnimatedInteractionMesh::interaction_mesh_adjacency_iterator_t
typedef boost::graph_traits<interaction_mesh_graph_t>::edge_descriptor roboptim::retargeting::AnimatedInteractionMesh::interaction_mesh_edge_descriptor_t
typedef boost::graph_traits<interaction_mesh_graph_t>::edge_iterator roboptim::retargeting::AnimatedInteractionMesh::interaction_mesh_edge_iterator_t
typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::undirectedS, InteractionMeshVertex, InteractionMeshEdge> roboptim::retargeting::AnimatedInteractionMesh::interaction_mesh_graph_t
Graph used to represent the interaction mesh.
typedef boost::property_map< interaction_mesh_graph_t, boost::vertex_index_t>::type roboptim::retargeting::AnimatedInteractionMesh::interaction_mesh_index_map_t
typedef boost::graph_traits<interaction_mesh_graph_t>::out_edge_iterator roboptim::retargeting::AnimatedInteractionMesh::interaction_mesh_out_edge_iterator_t
typedef boost::graph_traits<interaction_mesh_graph_t>::vertex_descriptor roboptim::retargeting::AnimatedInteractionMesh::interaction_mesh_vertex_descriptor_t
typedef boost::graph_traits<interaction_mesh_graph_t>::vertex_iterator roboptim::retargeting::AnimatedInteractionMesh::interaction_mesh_vertex_iterator_t
typedef boost::graph_traits<graph_t>::out_edge_iterator roboptim::retargeting::AnimatedInteractionMesh::out_edge_iterator_t
typedef boost::graph_traits<graph_t>::vertex_descriptor roboptim::retargeting::AnimatedInteractionMesh::vertex_descriptor_t
typedef boost::graph_traits<graph_t>::vertex_iterator roboptim::retargeting::AnimatedInteractionMesh::vertex_iterator_t
Constructor & Destructor Documentation
roboptim::retargeting::AnimatedInteractionMesh::AnimatedInteractionMesh () [explicit]
roboptim::retargeting::AnimatedInteractionMesh::~AnimatedInteractionMesh ()
Member Function Documentation
void roboptim::retargeting::AnimatedInteractionMesh::computeInteractionMesh (unsigned frameId)
References graph(), and numVertices().
Referenced by computeInteractionMeshes().
void roboptim::retargeting::AnimatedInteractionMesh::computeInteractionMeshes ()
References computeInteractionMesh(), and numFrames().
Referenced by recomputeCachedData().
void roboptim::retargeting::AnimatedInteractionMesh::computeVertexWeights ()
Compute current edges weights based on vertices positions.
Each time a vertex position is updated the weights are invalidated and should be recomputed.
References graph(), interactionMeshes(), roboptim::retargeting::Vertex::positions, and roboptim::retargeting::InteractionMeshEdge::weight.
Referenced by recomputeCachedData().
const double& roboptim::retargeting::AnimatedInteractionMesh::framerate () const [inline]
AnimatedInteractionMesh::vertex_iterator_t roboptim::retargeting::AnimatedInteractionMesh::getVertexFromLabel (const std::string & label) const
References graph().
AnimatedInteractionMesh::vertex_iterator_t roboptim::retargeting::AnimatedInteractionMesh::getVertexFromPosition (unsigned frameId, double x, double y, double z) const
References graph().
const graph_t& roboptim::retargeting::AnimatedInteractionMesh::graph () const [inline]
Referenced by computeInteractionMesh(), computeVertexWeights(), getVertexFromLabel(), getVertexFromPosition(), recomputeCachedData(), writeGraphvizGraphs(), and writeTrajectory().
graph_t& roboptim::retargeting::AnimatedInteractionMesh::graph () [inline]
const std::vector<interaction_mesh_graph_t>& roboptim::retargeting::AnimatedInteractionMesh::interactionMeshes () const [inline]
Referenced by computeVertexWeights().
std::vector<interaction_mesh_graph_t>& roboptim::retargeting::AnimatedInteractionMesh::interactionMeshes () [inline]
AnimatedInteractionMeshShPtr_t roboptim::retargeting::AnimatedInteractionMesh::loadAnimatedMesh (cnoid::MarkerMotionPtr markerMotion, cnoid::CharacterPtr character) [static]
References roboptim::retargeting::checkNodeType().
void roboptim::retargeting::AnimatedInteractionMesh::loadEdgesFromYaml (const YAML::Node & node, AnimatedInteractionMeshShPtr_t animatedMesh) [static, protected]
AnimatedInteractionMeshShPtr_t roboptim::retargeting::AnimatedInteractionMesh::makeFromOptimizationVariables (const Eigen::Matrix< double, Eigen::Dynamic, 1 > & x, AnimatedInteractionMeshShPtr_t previousAnimatedMesh) [static]
Referenced by roboptim::retargeting::problem::Joint::Joint(), and roboptim::retargeting::problem::Marker::Marker().
const Eigen::VectorXd& roboptim::retargeting::AnimatedInteractionMesh::makeOptimizationVector () const [inline]
Eigen::VectorBlock<const Eigen::VectorXd, Eigen::Dynamic> roboptim::retargeting::AnimatedInteractionMesh::makeOptimizationVectorOneFrame (unsigned frameId) const [inline]
References optimizationVectorSizeOneFrame().
Referenced by writeTrajectory().
unsigned roboptim::retargeting::AnimatedInteractionMesh::numFrames () const [inline]
Referenced by computeInteractionMeshes(), and writeGraphvizGraphs().
unsigned roboptim::retargeting::AnimatedInteractionMesh::numVertices () const [inline]
Referenced by computeInteractionMesh().
std::size_t roboptim::retargeting::AnimatedInteractionMesh::optimizationVectorSize () const [inline]
std::size_t roboptim::retargeting::AnimatedInteractionMesh::optimizationVectorSizeOneFrame () const [inline]
Referenced by makeOptimizationVectorOneFrame().
void roboptim::retargeting::AnimatedInteractionMesh::recomputeCachedData ()
Recompute cached data using graph.
References computeInteractionMeshes(), computeVertexWeights(), and graph().
Eigen::VectorXd& roboptim::retargeting::AnimatedInteractionMesh::state () [inline]
Access the interal vector directly.
Warning: this API is unsafe, it is your responsibility to update edges weights if you modify the state manually.
const Eigen::VectorXd& roboptim::retargeting::AnimatedInteractionMesh::state () const [inline]
void roboptim::retargeting::AnimatedInteractionMesh::writeGraphvizGraphs (std::ostream & out, unsigned id)
References graph().
Referenced by writeGraphvizGraphs().
void roboptim::retargeting::AnimatedInteractionMesh::writeGraphvizGraphs (const std::string & path)
References numFrames(), writeGraphvizGraphs(), and writeGraphvizInteractionMeshGraphs().
void roboptim::retargeting::AnimatedInteractionMesh::writeGraphvizInteractionMeshGraphs (std::ostream & out, unsigned id)
Referenced by writeGraphvizGraphs().
void roboptim::retargeting::AnimatedInteractionMesh::writeTrajectory (const std::string & filename)
References graph(), and makeOptimizationVectorOneFrame().