roboptim::retargeting Namespace Reference
roboptim::retargeting Namespace Reference
Namespaces
namespace detail
Classes
class BodyLaplacianDeformationEnergyChoreonoid2
Body Laplacian Deformation Energy (from laplacian coordinates, for one frame)
class BodyLaplacianDeformationEnergyChoreonoid
Laplacian Deformation Energy computed using Choreonoid Motion Capture plug-in.
class ChoreonoidBodyTrajectory
Discrete trajectory built from a cnoid::BodyMotion object.
class CostReferenceTrajectory
class DistanceToMarker
Distance between markers expected positions and reference markers positions.
class ForwardGeometryChoreonoid
Compute forward geometry for a particular robot model.
class ForwardGeometry
Compute a particular body position for a given configuration.
class JointToMarkerPositionChoreonoid
Convert joint position into marker position.
class LaplacianCoordinateChoreonoid
Laplacian Coordinate of all markers of one frame.
class MinimumJerkTrajectory
Minimum jerk trajectory computation.
class TorqueChoreonoid
Torque position computed through Choreonoid.
class TorqueMetapod
Torque position computed through Metapod.
class Torque
Compute the Torque of each joint.
class ZMPChoreonoid
ZMP position computed through Choreonoid.
class ZMPInvertedPendulum
ZMP position computed using the Inverted Pendulum model.
class ZMPMetapod
ZMP position computed through Metapod.
class ZMP
Abstract class for Computing the ZMP position.
struct Constraint
Constraint definition.
class FunctionFactory
Function factories inherit from this class (empty for now).
struct JointFunctionData
POD structure containing all problems data.
class JointFunctionFactory
Creates functions from their name for joint-joint optimization.
struct JointProblemOptions
Joint optimization problem description.
class JointProblemBuilder
Build a joint retargeting problem.
struct MarkerFunctionData
POD structure containing all problems data.
class MarkerFunctionFactory
Creates functions from their name for marker-joint optimization.
struct MarkerProblemOptions
Marker optimization problem description.
class MarkerProblemBuilder
Build a marker retargeting problem.
struct MarkerToJointFunctionData
POD structure containing all problems data.
class MarkerToJointFunctionFactory
Creates functions from their name for joint-joint optimization.
struct MarkerToJointProblemOptions
Joint optimization problem description.
class MarkerToJointProblemBuilder
Build a joint retargeting problem.
class ProblemBuilder
Abstract Base Class for problem builders.
Typedefs
typedef roboptim::Problem
< roboptim::GenericDifferentiableFunction
< EigenMatrixDense >
, boost::mpl::vector
< roboptim::GenericLinearFunction
< EigenMatrixDense >
, roboptim::GenericDifferentiableFunction
< EigenMatrixDense > > > denseProblem_t
Define dense problem type.
typedef roboptim::Problem
< roboptim::GenericDifferentiableFunction
< EigenMatrixSparse >
, boost::mpl::vector
< roboptim::GenericLinearFunction
< EigenMatrixSparse >
, roboptim::GenericDifferentiableFunction
< EigenMatrixSparse > > > sparseProblem_t
Define sparse problem type.
Functions
template<typename T >
boost::shared_ptr
< GenericDifferentiableFunction
< T > > acceleration ()
Compute acceleration from position.
template<typename T >
std::ostream & printMatrix (std::ostream &o, const Eigen::MatrixBase< T > &matrix)
template<typename T >
std::ostream & operator<< (std::ostream &o, const std::set< T > &set)
std::ostream & operator<< (std::ostream &o, const cnoid::Link &link)
std::ostream & operator<< (std::ostream &o, const cnoid::BodyMotion &bodyMotion)
std::ostream & operator<< (std::ostream &o, const cnoid::BodyIMesh::Marker &marker)
std::ostream & operator<< (std::ostream &o, const cnoid::BodyIMesh::BodyInfo &bodyInfo)
std::ostream & operator<< (std::ostream &o, const cnoid::BodyIMesh &mesh)
template<typename Derived >
void updateRobotConfiguration (const cnoid::BodyPtr &robot, const Eigen::MatrixBase< Derived > &x)
Update Choreonoid robot from configuration vector.
template<typename T >
void plotQ (const T &state)
void buildJointDataFromOptions (JointFunctionData &data, const JointProblemOptions &options)
Build joint problem data from problem description.
std::vector< boost::optional
< Function::value_type > > disabledJointsConfiguration (const std::vector< std::string > &disabledJoints, boost::shared_ptr< Trajectory< 3 > > originalTrajectory, cnoid::BodyPtr robotModel)
Store which joints are disabled and what value they should be set in this case.
boost::shared_ptr< Trajectory< 3 > > filterTrajectory (boost::shared_ptr< Trajectory< 3 > > originalTrajectory, const std::vector< boost::optional< Function::value_type > > &disabledJointsConfiguration)
Copy a trajectory while excluding some joints.
void buildDataFromOptions (MarkerFunctionData &data, const MarkerProblemOptions &options)
Build marker problem data from problem description.
template<typename T >
boost::shared_ptr< T > convertToTrajectory (const libmocap::MarkerTrajectory &raw)
Convert markers trajectories to a RobOptim trajectory.
void buildMarkerToJointDataFromOptions (MarkerToJointFunctionData &data, const MarkerToJointProblemOptions &options)
Build joint problem data from problem description.
Typedef Documentation
typedef roboptim::Problem< roboptim::GenericDifferentiableFunction<EigenMatrixDense>, boost::mpl::vector< roboptim::GenericLinearFunction<EigenMatrixDense>, roboptim::GenericDifferentiableFunction<EigenMatrixDense> > > roboptim::retargeting::denseProblem_t
Define dense problem type.
typedef roboptim::Problem< roboptim::GenericDifferentiableFunction<EigenMatrixSparse>, boost::mpl::vector< roboptim::GenericLinearFunction<EigenMatrixSparse>, roboptim::GenericDifferentiableFunction<EigenMatrixSparse> > > roboptim::retargeting::sparseProblem_t
Define sparse problem type.
Function Documentation
template<typename T > boost::shared_ptr<GenericDifferentiableFunction<T> > roboptim::retargeting::acceleration ()
Compute acceleration from position.
Use second derivative as acceleration.
VectorInterpolation should be used here for implementation.
void roboptim::retargeting::buildDataFromOptions (MarkerFunctionData & data, const MarkerProblemOptions & options) [inline]
Build marker problem data from problem description.
The MarkerProblemData structure contains the real loaded data where the MarkerProblemOptions just describe the problem a set of strings (usually retrieved from the user).
This function will load the motion capture data, robot model, etc.
Note:
A failure at this stage is not fatal. Robot model for instance may be omitted if the segment length constraint is disabled. However, a fatal error however may occur when the constraints are allocated if a required data is missing from this structure.
Parameters:
[out] data structure to contain the loaded data
[in] options problem description
References roboptim::retargeting::MarkerProblemOptions::markerSet, roboptim::retargeting::MarkerFunctionData::markerSet, roboptim::retargeting::MarkerFunctionData::markersTrajectory, roboptim::retargeting::MarkerProblemOptions::markersTrajectory, roboptim::retargeting::MarkerFunctionData::robotModel, roboptim::retargeting::MarkerProblemOptions::robotModel, roboptim::retargeting::MarkerFunctionData::trajectory, and roboptim::retargeting::MarkerProblemOptions::trajectoryType.
Referenced by roboptim::retargeting::MarkerProblemBuilder< T >::operator()().
void roboptim::retargeting::buildJointDataFromOptions (JointFunctionData & data, const JointProblemOptions & options) [inline]
Build joint problem data from problem description.
The JointProblemData structure contains the loaded data whereas the JointProblemOptions just describe the problem a set of strings (usually retrieved from the user).
This function will load the joints trajectories, robot model, etc.
Note:
A failure at this stage is not fatal. Some data loading may be skipped with a warning message. However, a fatal error however may occur when the constraints are allocated if a required data is missing from this structure.
Parameters:
[out] data structure to contain the loaded data
[in] options problem description
References roboptim::retargeting::JointProblemOptions::disabledJoints, roboptim::retargeting::JointFunctionData::disabledJointsConfiguration, disabledJointsConfiguration(), roboptim::retargeting::JointFunctionData::disabledJointsTrajectory, roboptim::retargeting::JointFunctionData::filteredTrajectory, filterTrajectory(), roboptim::retargeting::JointFunctionData::interactionMesh, roboptim::retargeting::JointProblemOptions::jointsTrajectory, roboptim::retargeting::JointFunctionData::jointsTrajectory, roboptim::retargeting::JointFunctionData::nFrames(), roboptim::retargeting::JointFunctionData::robotModel, roboptim::retargeting::JointProblemOptions::robotModel, roboptim::retargeting::JointFunctionData::trajectory, and roboptim::retargeting::JointProblemOptions::trajectoryType.
Referenced by roboptim::retargeting::JointProblemBuilder< T >::operator()().
void roboptim::retargeting::buildMarkerToJointDataFromOptions (MarkerToJointFunctionData & data, const MarkerToJointProblemOptions & options)
Build joint problem data from problem description.
The JointProblemData structure contains the loaded data whereas the JointProblemOptions just describe the problem a set of strings (usually retrieved from the user).
This function will load the joints trajectories, robot model, etc.
Note:
A failure at this stage is not fatal. Some data loading may be skipped with a warning message. However, a fatal error however may occur when the constraints are allocated if a required data is missing from this structure.
Parameters:
[out] data structure to contain the loaded data
[in] options problem description
References roboptim::retargeting::MarkerToJointProblemOptions::disabledJoints, roboptim::retargeting::MarkerToJointFunctionData::disabledJointsConfiguration, disabledJointsConfiguration(), roboptim::retargeting::MarkerToJointProblemOptions::frameId, roboptim::retargeting::MarkerToJointFunctionData::frameId, roboptim::retargeting::MarkerToJointFunctionData::initialized, roboptim::retargeting::MarkerToJointFunctionData::inputTrajectory, roboptim::retargeting::MarkerToJointFunctionData::interactionMesh, roboptim::retargeting::MarkerToJointProblemOptions::markerSet, roboptim::retargeting::MarkerToJointFunctionData::markerSet, roboptim::retargeting::MarkerToJointProblemOptions::markersTrajectory, roboptim::retargeting::MarkerToJointFunctionData::markersTrajectory, roboptim::retargeting::MarkerToJointFunctionData::outputTrajectory, roboptim::retargeting::MarkerToJointFunctionData::outputTrajectoryReduced, roboptim::retargeting::MarkerToJointProblemOptions::robotModel, roboptim::retargeting::MarkerToJointFunctionData::robotModel, and roboptim::retargeting::MarkerToJointProblemOptions::trajectoryType.
Referenced by roboptim::retargeting::MarkerToJointProblemBuilder< T >::operator()().
template<typename T > boost::shared_ptr<T> roboptim::retargeting::convertToTrajectory (const libmocap::MarkerTrajectory & raw)
Convert markers trajectories to a RobOptim trajectory.
The trajectory output size matches the number of marker, the input size is time.
The data from libmocap is copied frame per frame into the new object.
std::vector<boost::optional<Function::value_type> > roboptim::retargeting::disabledJointsConfiguration (const std::vector< std::string > & disabledJoints, boost::shared_ptr< Trajectory< 3 > > originalTrajectory, cnoid::BodyPtr robotModel)
Store which joints are disabled and what value they should be set in this case.
By default, all joints are enabled.
The user can also pass a set of joints to be filtered out before starting the optimization process. The joints are described by their name.
Invalid joint names or duplicated joint are illegal.
This function build the set of enabled joints from this vector of strings. This is represented by a vector of optional values. The index is the joint id (0...6 is free-floating then the joints configurations). The vector value is either empty (the joint value will be determined by the optimization process) or defined to a constant. In the latter case, the joint is excluded from the optimization process and will always be equal to this value. The constant (default) value of the joint is the value of its joint in the first frame of the joint trajectory.
Parameters:
[in] disabledJoints list of joints to be excluded from the optimization process and identified by their name
[in] originalTrajectory full joint trajectory
[in] robotModel robot model loaded by Choreonoid and providing the joint name to index mapping
Returns:
vector of enabled and disabled joints (no value means that joint is disabled, i.e. not to be taken into account during the optimization process and a value means this joint will be excluded from the optimization process and always take this value).
Referenced by buildJointDataFromOptions(), buildMarkerToJointDataFromOptions(), and filterTrajectory().
boost::shared_ptr<Trajectory<3> > roboptim::retargeting::filterTrajectory (boost::shared_ptr< Trajectory< 3 > > originalTrajectory, const std::vector< boost::optional< Function::value_type > > & disabledJointsConfiguration)
Copy a trajectory while excluding some joints.
Parameters:
[in] originalTrajectory original, full, trajectory
[in] disabledJointsConfiguration list of joints to be excluded
Returns:
filtered trajectory
References disabledJointsConfiguration().
Referenced by buildJointDataFromOptions().
template<typename T > std::ostream& roboptim::retargeting::operator<< (std::ostream & o, const std::set< T > & set)
std::ostream& roboptim::retargeting::operator<< (std::ostream & o, const cnoid::Link & link)
std::ostream& roboptim::retargeting::operator<< (std::ostream & o, const cnoid::BodyMotion & bodyMotion)
std::ostream& roboptim::retargeting::operator<< (std::ostream & o, const cnoid::BodyIMesh::Marker & marker)
std::ostream& roboptim::retargeting::operator<< (std::ostream & o, const cnoid::BodyIMesh::BodyInfo & bodyInfo)
std::ostream& roboptim::retargeting::operator<< (std::ostream & o, const cnoid::BodyIMesh & mesh)
template<typename T > void roboptim::retargeting::plotQ (const T & state)
template<typename T > std::ostream& roboptim::retargeting::printMatrix (std::ostream & o, const Eigen::MatrixBase< T > & matrix)
template<typename Derived > void roboptim::retargeting::updateRobotConfiguration (const cnoid::BodyPtr & robot, const Eigen::MatrixBase< Derived > & x)
Update Choreonoid robot from configuration vector.
It is a two step process: 1. extract the first 6 DOFs of the configuration vector which represents the root link position. The first three values are the translation part, The next three values are the rotational part expressed using the U-Theta representation.
2. The remaining values are the DOFs configurations, pass them directly to Choreonoid.
This function does not realize any allocation and can be safely used in function computations.
Parameters:
robot Choreonoid robot
x configuration vector which size must correspond to the robot number of DOFs plus six.
References eulerToTransform().
Referenced by roboptim::retargeting::ZMPChoreonoid< T >::fillStates(), roboptim::retargeting::TorqueChoreonoid< T >::impl_compute(), roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::impl_compute(), roboptim::retargeting::ForwardGeometryChoreonoid< T >::impl_compute(), roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::impl_gradient(), roboptim::retargeting::ForwardGeometryChoreonoid< T >::impl_gradient2(), roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::impl_jacobian(), and roboptim::retargeting::ForwardGeometryChoreonoid< T >::impl_jacobian2().