roboptim::retargeting::JointToMarkerPositionChoreonoid< T > Class Template Reference
roboptim::retargeting::JointToMarkerPositionChoreonoid< T > Class Template Reference
Convert joint position into marker position.
#include <roboptim/retargeting/function/joint-to-marker/choreonoid.hh>
Public Member Functions
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
JointToMarkerPositionChoreonoid (cnoid::BodyIMeshPtr mesh) throw (std::runtime_error)
virtual ~JointToMarkerPositionChoreonoid () throw ()
Protected Member Functions
void impl_compute (result_t &result, const argument_t &x) const throw ()
void impl_gradient (gradient_t &gradient, const argument_t &x, size_type functionId) const throw ()
void impl_jacobian (jacobian_t &jacobian, const argument_t &x) const throw ()
template<typename Derived >
void updateDR (const typename Eigen::MatrixBase< Derived > &x) const throw ()
Detailed Description
template<typename T>
class roboptim::retargeting::JointToMarkerPositionChoreonoid< T >
Convert joint position into marker position.
Input: [q] where q is the value of a particular joint [q] is the full robot configuration including the free-floating joint.
Output: [m] where m is a marker position in the 3d space (x, y, z) [m] is the array of all markers associated with the character
The joint/marker offset is constant.
Constructor & Destructor Documentation
template<typename T > roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::JointToMarkerPositionChoreonoid (cnoid::BodyIMeshPtr mesh) throw (std::runtime_error) [inline, explicit]
template<typename T > virtual roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::~JointToMarkerPositionChoreonoid () throw () [inline, virtual]
Member Function Documentation
template<typename T > void roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::impl_compute (result_t & result, const argument_t & x) const throw () [inline, protected]
References roboptim::retargeting::updateRobotConfiguration().
template<typename T > void roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::impl_gradient (gradient_t & gradient, const argument_t & x, size_type functionId) const throw () [inline, protected]
References hat(), roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::updateDR(), and roboptim::retargeting::updateRobotConfiguration().
template<typename T > void roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::impl_jacobian (jacobian_t & jacobian, const argument_t & x) const throw () [inline, protected]
References hat(), roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::updateDR(), and roboptim::retargeting::updateRobotConfiguration().
template<typename T > roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
template<typename T > template<typename Derived > void roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::updateDR (const typename Eigen::MatrixBase< Derived > & x) const throw () [inline, protected]
Referenced by roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::impl_gradient(), and roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::impl_jacobian().