roboptim::retargeting::JointProblemBuilder< T > Class Template Reference
roboptim::retargeting::JointProblemBuilder< T > Class Template Reference
Build a joint retargeting problem.
#include <roboptim/retargeting/problem/joint-problem-builder.hh>
Public Member Functions
void operator() (boost::shared_ptr< T > &problem, JointFunctionData &data)
Instantiate the problem and return it.
JointProblemBuilder (const JointProblemOptions &options)
Constructor and destructor.
~JointProblemBuilder ()
Detailed Description
template<typename T>
class roboptim::retargeting::JointProblemBuilder< T >
Build a joint retargeting problem.
This class is in charge of building the optimization problem: the cost function, the constraints (function, intervals, scale) and will set the starting point of the optimization process.
It will also load the data that which will be used by the constraints function.
This class is parametrized by T, the problem type. By changing the problem type, sparse problems can also be solved.
Template Parameters:
T problem type
Constructor & Destructor Documentation
template<typename T > roboptim::retargeting::JointProblemBuilder< T >::JointProblemBuilder (const JointProblemOptions & options)
Constructor and destructor.
Constructor
Warning:
options are kept as a const reference so this object lifespan much be longer than the one of this object.
Parameters:
[in] options problem description
template<typename T > roboptim::retargeting::JointProblemBuilder< T >::~JointProblemBuilder ()
Member Function Documentation
template<typename T > void roboptim::retargeting::JointProblemBuilder< T >::operator() (boost::shared_ptr< T > & problem, JointFunctionData & data)
Instantiate the problem and return it.
Returns:
shared pointer containing the newly created problem.
References roboptim::retargeting::JointFunctionFactory::buildConstraint(), roboptim::retargeting::JointFunctionFactory::buildFunction(), roboptim::retargeting::buildJointDataFromOptions(), roboptim::retargeting::JointFunctionData::cost, roboptim::retargeting::JointFunctionData::disabledJointsTrajectory, roboptim::retargeting::JointFunctionData::filteredTrajectory, roboptim::retargeting::Constraint< T >::function, roboptim::retargeting::Constraint< T >::intervals, roboptim::retargeting::JointFunctionData::nFrames(), roboptim::retargeting::Constraint< T >::scales, roboptim::retargeting::Constraint< T >::stateFunctionOrder, and roboptim::retargeting::Constraint< T >::type.