roboptim::retargeting::detail Namespace Reference
roboptim::retargeting::detail Namespace Reference
Classes
class DistanceToReference
Quadratic function computing the distance between a vector and a reference.
struct JointFunctionFactoryMapping
Map function name to the function used to allocate them.
struct MarkerFunctionFactoryMapping
Map function name to the function used to allocate them.
struct MarkerToJointFunctionFactoryMapping
Map function name to the function used to allocate them.
Functions
template<typename T >
boost::shared_ptr
< GenericDifferentiableFunction
< T > > distanceToMarkerInternal (const typename GenericDifferentiableFunction< T >::vector_t &references, boost::shared_ptr< GenericDifferentiableFunction< T > > jointToMarker)
template<typename T >
boost::shared_ptr< T > null (const JointFunctionData &data)
template<typename T >
boost::shared_ptr< T > freeze (const JointFunctionData &data)
template<typename T >
boost::shared_ptr< T > leftFoot (const JointFunctionData &data)
template<typename T >
boost::shared_ptr< T > rightFoot (const JointFunctionData &data)
template<typename T >
boost::shared_ptr< T > jointsLimits (const JointFunctionData &data)
template<typename T >
boost::shared_ptr< T > laplacianDeformationEnergy (const JointFunctionData &data)
template<typename T >
boost::shared_ptr< T > torque (const JointFunctionData &data)
template<typename T >
boost::shared_ptr< T > zmp (const JointFunctionData &data)
template<typename T >
boost::shared_ptr< T > null (const MarkerFunctionData &data)
template<typename T >
boost::shared_ptr< T > laplacianDeformationEnergy (const MarkerFunctionData &)
template<typename T >
boost::shared_ptr< T > boneLength (const MarkerFunctionData &)
template<typename T >
boost::shared_ptr< T > null (const MarkerToJointFunctionData &data)
template<typename T >
boost::shared_ptr< T > distanceToMarker (const MarkerToJointFunctionData &data)
template<typename T >
boost::shared_ptr< T > jointsLimits (const MarkerToJointFunctionData &data)
Function Documentation
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::boneLength (const MarkerFunctionData &)
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::distanceToMarker (const MarkerToJointFunctionData & data)
References roboptim::retargeting::MarkerToJointFunctionData::frameId, roboptim::retargeting::MarkerToJointFunctionData::inputTrajectory, and roboptim::retargeting::MarkerToJointFunctionData::interactionMesh.
template<typename T > boost::shared_ptr<GenericDifferentiableFunction<T> > roboptim::retargeting::detail::distanceToMarkerInternal (const typename GenericDifferentiableFunction< T >::vector_t & references, boost::shared_ptr< GenericDifferentiableFunction< T > > jointToMarker)
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::freeze (const JointFunctionData & data)
References roboptim::retargeting::JointFunctionData::filteredTrajectory, roboptim::retargeting::JointFunctionData::nDofsFiltered(), and roboptim::retargeting::JointFunctionData::nParametersFiltered().
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::jointsLimits (const MarkerToJointFunctionData & data)
References roboptim::retargeting::MarkerToJointFunctionData::nDofsFiltered().
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::jointsLimits (const JointFunctionData & data)
References roboptim::retargeting::JointFunctionData::nDofsFiltered().
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::laplacianDeformationEnergy (const MarkerFunctionData &)
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::laplacianDeformationEnergy (const JointFunctionData & data)
References roboptim::retargeting::JointFunctionData::disabledJointsTrajectory, roboptim::retargeting::JointFunctionData::interactionMesh, and roboptim::retargeting::JointFunctionData::trajectory.
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::leftFoot (const JointFunctionData & data)
References roboptim::retargeting::JointFunctionData::robotModel.
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::null (const MarkerFunctionData & data)
References roboptim::retargeting::MarkerFunctionData::trajectory.
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::null (const MarkerToJointFunctionData & data)
References roboptim::retargeting::MarkerToJointFunctionData::nDofsFiltered(), and roboptim::retargeting::MarkerToJointFunctionData::outputTrajectoryReduced.
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::null (const JointFunctionData & data)
References roboptim::retargeting::JointFunctionData::trajectory.
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::rightFoot (const JointFunctionData & data)
References roboptim::retargeting::JointFunctionData::robotModel.
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::torque (const JointFunctionData & data)
References roboptim::retargeting::JointFunctionData::robotModel.
template<typename T > boost::shared_ptr<T> roboptim::retargeting::detail::zmp (const JointFunctionData & data)
References roboptim::retargeting::JointFunctionData::robotModel.