roboptim::retargeting::TorqueMetapod< T, R > Class Template Reference
roboptim::retargeting::TorqueMetapod< T, R > Class Template Reference
Torque position computed through Metapod.
#include <roboptim/retargeting/function/torque/metapod.hh>
Public Types
typedef R robot_t
Public Member Functions
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (Torque< T >)
TorqueMetapod () throw ()
virtual ~TorqueMetapod () throw ()
void impl_compute (result_t &result, const argument_t &x) const throw ()
void impl_gradient (gradient_t &gradient, const argument_t &x, size_type i) const throw ()
Detailed Description
template<typename T, typename R>
class roboptim::retargeting::TorqueMetapod< T, R >
Torque position computed through Metapod.
You *have* to make sure that your model root joint is a floating joint here.
Template Parameters:
T Function traits type
R Robot type
Member Typedef Documentation
template<typename T , typename R > typedef R roboptim::retargeting::TorqueMetapod< T, R >::robot_t
Constructor & Destructor Documentation
template<typename T , typename R > roboptim::retargeting::TorqueMetapod< T, R >::TorqueMetapod () throw () [inline, explicit]
template<typename T , typename R > virtual roboptim::retargeting::TorqueMetapod< T, R >::~TorqueMetapod () throw () [inline, virtual]
Member Function Documentation
template<typename T , typename R > void roboptim::retargeting::TorqueMetapod< T, R >::impl_compute (result_t & result, const argument_t & x) const throw () [inline]
References roboptim::retargeting::Torque< T >::ddq(), roboptim::retargeting::Torque< T >::dq(), and roboptim::retargeting::Torque< T >::q().
template<typename T , typename R > void roboptim::retargeting::TorqueMetapod< T, R >::impl_gradient (gradient_t & gradient, const argument_t & x, size_type i) const throw () [inline]
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
template<typename T , typename R > roboptim::retargeting::TorqueMetapod< T, R >::ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (Torque< T >)