roboptim::retargeting::ZMPChoreonoid< T > Class Template Reference
roboptim::retargeting::ZMPChoreonoid< T > Class Template Reference
ZMP position computed through Choreonoid.
#include <roboptim/retargeting/function/zmp/choreonoid.hh>
Classes
struct State
Public Member Functions
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (ZMP< T >)
ZMPChoreonoid (cnoid::BodyPtr robot) throw ()
ZMPChoreonoid (const ZMPChoreonoid< T > &zmp) throw ()
ZMPChoreonoid< T > & operator= (const ZMPChoreonoid< T > &rhs)
virtual ~ZMPChoreonoid () throw ()
const State & states () const throw ()
void printState (std::ostream &o, std::size_t i) const throw ()
void printQuantities (std::ostream &o) const throw ()
Protected Member Functions
void fillStates (const argument_t &x) const throw ()
void impl_compute (result_t &result, const argument_t &x) const throw ()
void impl_gradient (gradient_t &gradient, const argument_t &x, size_type i) const throw ()
Detailed Description
template<typename T>
class roboptim::retargeting::ZMPChoreonoid< T >
ZMP position computed through Choreonoid.
Template Parameters:
T Function traits type
Constructor & Destructor Documentation
template<typename T> roboptim::retargeting::ZMPChoreonoid< T >::ZMPChoreonoid (cnoid::BodyPtr robot) throw () [inline, explicit]
template<typename T> roboptim::retargeting::ZMPChoreonoid< T >::ZMPChoreonoid (const ZMPChoreonoid< T > & zmp) throw () [inline, explicit]
template<typename T> virtual roboptim::retargeting::ZMPChoreonoid< T >::~ZMPChoreonoid () throw () [inline, virtual]
Member Function Documentation
template<typename T> void roboptim::retargeting::ZMPChoreonoid< T >::fillStates (const argument_t & x) const throw () [inline, protected]
References roboptim::retargeting::ZMP< T >::ddq(), roboptim::retargeting::ZMP< T >::dq(), roboptim::retargeting::ZMP< T >::q(), and roboptim::retargeting::updateRobotConfiguration().
Referenced by roboptim::retargeting::ZMPChoreonoid< T >::impl_compute().
template<typename T> void roboptim::retargeting::ZMPChoreonoid< T >::impl_compute (result_t & result, const argument_t & x) const throw () [inline, protected]
References roboptim::retargeting::ZMPChoreonoid< T >::fillStates().
template<typename T> void roboptim::retargeting::ZMPChoreonoid< T >::impl_gradient (gradient_t & gradient, const argument_t & x, size_type i) const throw () [inline, protected]
template<typename T> ZMPChoreonoid<T>& roboptim::retargeting::ZMPChoreonoid< T >::operator= (const ZMPChoreonoid< T > & rhs) [inline]
template<typename T> void roboptim::retargeting::ZMPChoreonoid< T >::printQuantities (std::ostream & o) const throw () [inline]
References roboptim::retargeting::ZMPChoreonoid< T >::printState().
template<typename T> void roboptim::retargeting::ZMPChoreonoid< T >::printState (std::ostream & o, std::size_t i) const throw () [inline]
Referenced by roboptim::retargeting::ZMPChoreonoid< T >::printQuantities().
template<typename T> roboptim::retargeting::ZMPChoreonoid< T >::ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (ZMP< T >)
template<typename T> const State& roboptim::retargeting::ZMPChoreonoid< T >::states () const throw () [inline]