eigen-rigid-body.hh File Reference
eigen-rigid-body.hh File Reference
#include <roboptim/core/function.hh>
#include <roboptim/retargeting/eigen-rigid-body.hxx>
Functions
template<typename Derived , typename OtherDerived >
void eulerToTransform (Eigen::MatrixBase< Derived > const &transform, const Eigen::MatrixBase< OtherDerived > &eulerAngles)
Set the rotational part of a transformation from Euler angles parameters.
template<typename Derived , typename OtherDerived >
void uthetaToTransform (Eigen::MatrixBase< Derived > const &transform, const Eigen::MatrixBase< OtherDerived > &utheta)
Set the rotational part of a transformation from U parameters (three parameters version).
template<typename Derived , typename OtherDerived >
void transformToEuler (Eigen::MatrixBase< Derived > const &eulerAngles, const Eigen::MatrixBase< OtherDerived > &linear)
Compute Euler angles parameters from a rotation matrix.
template<typename Derived , typename OtherDerived >
void transformToUTheta (Eigen::MatrixBase< Derived > const &utheta, const Eigen::MatrixBase< OtherDerived > &linear)
Compute U parameters from a rotation matrix.
template<typename Derived , typename OtherDerived >
void hat (Eigen::MatrixBase< Derived > const &result, const Eigen::MatrixBase< OtherDerived > &p)
Build a skew-symmetric matrix from vector of size 3.
template<typename Derived >
Eigen::Matrix< typename
Derived::RealScalar, 3, 3 > hat (const Eigen::MatrixBase< Derived > &p)
Build a skew-symmetric matrix from vector of size 3.
template<typename Derived , int _Dim, int _Mode, int _Options>
void adjoint (Eigen::MatrixBase< Derived > const &adjoint, const Eigen::Transform< typename Derived::RealScalar, _Dim, _Mode, _Options > &transform)
Build a transformation adjoint.
template<typename Derived , int _Dim, int _Mode, int _Options>
void transformToVector (Eigen::MatrixBase< Derived > const &result, const Eigen::Transform< typename Derived::RealScalar, _Dim, _Mode, _Options > &transform)
Store a transformation as a vector.
template<typename Derived , int _Dim, int _Mode, int _Options>
void transformToUtheta (Eigen::MatrixBase< Derived > const &result, const Eigen::Transform< typename Derived::RealScalar, _Dim, _Mode, _Options > &transform)
Store a transformation as a vector.
template<typename Derived , int _Dim, int _Mode, int _Options>
void vectorToTransform (Eigen::Transform< typename Derived::RealScalar, _Dim, _Mode, _Options > &transform, const Eigen::MatrixBase< Derived > &vector)
Convert a vector to a transform.
template<typename Derived , int _Dim, int _Mode, int _Options>
void uthetaPoseToTransform (Eigen::Transform< typename Derived::RealScalar, _Dim, _Mode, _Options > &transform, const Eigen::MatrixBase< Derived > &result)
Convert a vector to a transform.
Function Documentation
template<typename Derived , int _Dim, int _Mode, int _Options> void adjoint (Eigen::MatrixBase< Derived > const & adjoint, const Eigen::Transform< typename Derived::RealScalar, _Dim, _Mode, _Options > & transform)
Build a transformation adjoint.
It must be applied to a twist written as: where is the
Formula
is the transformation rotation matrix (3x3). is the transformation translation vector (size 3).
Parameters:
[out] adjoint adjoint matrix (size 6x6)
[in] transform transformation
References adjoint(), and hat().
Referenced by adjoint().
template<typename Derived , typename OtherDerived > void eulerToTransform (Eigen::MatrixBase< Derived > const & transform, const Eigen::MatrixBase< OtherDerived > & eulerAngles)
Set the rotational part of a transformation from Euler angles parameters.
Formula
is the yaw parameter (rotation around Z axis) is the pitch parameter (rotation around Y axis) is the roll parameter (rotation around X axis)
Sources
http://planning.cs.uiuc.edu/node102.html
This implementation is an adaptation of the one in sot-core.
Parameters:
[out] eulerAngles vector
[in] transform store results
Referenced by roboptim::retargeting::updateRobotConfiguration(), and vectorToTransform().
template<typename Derived , typename OtherDerived > void hat (Eigen::MatrixBase< Derived > const & result, const Eigen::MatrixBase< OtherDerived > & p)
Build a skew-symmetric matrix from vector of size 3.
Formula
Parameters:
[out] result matrix (size 3x3)
[in] p
Referenced by adjoint(), hat(), roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::impl_gradient(), roboptim::retargeting::ForwardGeometryChoreonoid< T >::impl_gradient2(), roboptim::retargeting::JointToMarkerPositionChoreonoid< T >::impl_jacobian(), and roboptim::retargeting::ForwardGeometryChoreonoid< T >::impl_jacobian2().
template<typename Derived > Eigen::Matrix<typename Derived::RealScalar, 3, 3> hat (const Eigen::MatrixBase< Derived > & p)
Build a skew-symmetric matrix from vector of size 3.
See also:
hat(eulerAngles, transform)
Parameters:
[in] p
Returns:
hat matrix
References hat().
template<typename Derived , typename OtherDerived > void transformToEuler (Eigen::MatrixBase< Derived > const & eulerAngles, const Eigen::MatrixBase< OtherDerived > & linear)
Compute Euler angles parameters from a rotation matrix.
Notation
is the yaw parameter (rotation around Z axis) is the pitch parameter (rotation around Y axis) is the roll parameter (rotation around X axis)
Yaw
Pitch
Roll
Sources
http://planning.cs.uiuc.edu/node103.html
This implementation is an adaptation of the one in sot-core.
Parameters:
[out] eulerAngles vector
[in] linear rotation matrix
Referenced by transformToVector().
template<typename Derived , typename OtherDerived > void transformToUTheta (Eigen::MatrixBase< Derived > const & utheta, const Eigen::MatrixBase< OtherDerived > & linear)
Compute U parameters from a rotation matrix.
This relies on the Eigen::AngleAxis class.
Parameters:
[out] utheta vector
[in] linear rotation matrix
Referenced by transformToUtheta().
template<typename Derived , int _Dim, int _Mode, int _Options> void transformToUtheta (Eigen::MatrixBase< Derived > const & result, const Eigen::Transform< typename Derived::RealScalar, _Dim, _Mode, _Options > & transform)
Store a transformation as a vector.
The output vector contains three parameters for translation and three for the rotation ().
See also:
uthetaToTransform transformToUtheta
Parameters:
[out] result result vector
[in] transform input transformation
References transformToUTheta().
template<typename Derived , int _Dim, int _Mode, int _Options> void transformToVector (Eigen::MatrixBase< Derived > const & result, const Eigen::Transform< typename Derived::RealScalar, _Dim, _Mode, _Options > & transform)
Store a transformation as a vector.
The output vector contains three parameters for translation and three for the rotation (Euler angles).
See also:
eulerToTransform transformToEuler
Parameters:
[out] result result vector
[in] transform input transformation
References transformToEuler().
Referenced by roboptim::retargeting::ForwardGeometryChoreonoid< T >::impl_compute().
template<typename Derived , int _Dim, int _Mode, int _Options> void uthetaPoseToTransform (Eigen::Transform< typename Derived::RealScalar, _Dim, _Mode, _Options > & transform, const Eigen::MatrixBase< Derived > & result)
Convert a vector to a transform.
The input vector must three parameters for translation and three for the rotation (U).
See also:
uthetaToTransform transformToUTheta
Parameters:
[out] transform output transformation
[in] result vector
References uthetaToTransform().
template<typename Derived , typename OtherDerived > void uthetaToTransform (Eigen::MatrixBase< Derived > const & transform, const Eigen::MatrixBase< OtherDerived > & utheta)
Set the rotational part of a transformation from U parameters (three parameters version).
The three parameters encodes the rotation axis:
The vector norm encodes the amount of rotation around the rotation axis.
A notation exception is that if the norm is inferior to a threshold the rotation matrix is set to identity.
Parameters:
[out] utheta vector
[in] transform store results
Referenced by uthetaPoseToTransform().
template<typename Derived , int _Dim, int _Mode, int _Options> void vectorToTransform (Eigen::Transform< typename Derived::RealScalar, _Dim, _Mode, _Options > & transform, const Eigen::MatrixBase< Derived > & vector)
Convert a vector to a transform.
The input vector must three parameters for translation and three for the rotation (Euler angles).
See also:
eulerToTransform transformToEuler
Parameters:
[out] transform output transformation
[in] vector vector
References eulerToTransform().