roboptim::retargeting::JointFunctionFactory Class Reference
roboptim::retargeting::JointFunctionFactory Class Reference
Creates functions from their name for joint-joint optimization.
#include <roboptim/retargeting/problem/joint-function-factory.hh>
Public Member Functions
template<typename T >
boost::shared_ptr< T > buildFunction (const std::string &name)
Instantiate a function from its name.
template<typename T >
Constraint< T > buildConstraint (const std::string &name)
Instantiate a constraint from its name.
JointFunctionFactory (const JointFunctionData &data)
Constructor and Destructor.
~JointFunctionFactory ()
Static Public Member Functions
static std::vector< std::string > listFunctions ()
List supported functions.
Detailed Description
Creates functions from their name for joint-joint optimization.
Constructor & Destructor Documentation
roboptim::retargeting::JointFunctionFactory::JointFunctionFactory (const JointFunctionData & data) [explicit]
Constructor and Destructor.
Constructor
Parameters:
data problem data (trajectories, etc.)
roboptim::retargeting::JointFunctionFactory::~JointFunctionFactory ()
Member Function Documentation
template<typename T > Constraint< T > roboptim::retargeting::JointFunctionFactory::buildConstraint (const std::string & name)
Instantiate a constraint from its name.
This method creates a constraint object from the constraint name.
Parameters:
[in] name function name
Returns:
newly created constraint object
Template Parameters:
T function type (e.g. DifferentiableFunction)
References roboptim::retargeting::JointFunctionData::disabledJointsConfiguration, roboptim::retargeting::JointFunctionData::filteredTrajectory, roboptim::retargeting::Constraint< T >::function, roboptim::retargeting::Constraint< T >::intervals, roboptim::retargeting::JointFunctionData::nDofsFiltered(), roboptim::retargeting::JointFunctionData::nDofsFull(), roboptim::retargeting::JointFunctionData::robotModel, roboptim::retargeting::Constraint< T >::scales, roboptim::retargeting::Constraint< T >::stateFunctionOrder, and roboptim::retargeting::Constraint< T >::type.
Referenced by roboptim::retargeting::JointProblemBuilder< T >::operator()().
template<typename T > boost::shared_ptr< T > roboptim::retargeting::JointFunctionFactory::buildFunction (const std::string & name)
Instantiate a function from its name.
This method creates a function (cost or constraint) from its name.
Parameters:
[in] name function name
Returns:
shared pointer to the newly created function
Template Parameters:
T function type (e.g. DifferentiableFunction)
References roboptim::retargeting::detail::JointFunctionFactoryMapping< T >::Mapping::factory, and roboptim::retargeting::detail::JointFunctionFactoryMapping< T >::Mapping::name.
Referenced by roboptim::retargeting::JointProblemBuilder< T >::operator()().
std::vector< std::string > roboptim::retargeting::JointFunctionFactory::listFunctions () [inline, static]
List supported functions.
Each element of this string can be passed to buildFunction method to create the corresponding function.