roboptim::retargeting::ForwardGeometryChoreonoid< T > Class Template Reference
roboptim::retargeting::ForwardGeometryChoreonoid< T > Class Template Reference
Compute forward geometry for a particular robot model.
#include <roboptim/retargeting/function/forward-geometry/choreonoid.hh>
Public Member Functions
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (ForwardGeometry< T >)
ForwardGeometryChoreonoid (cnoid::BodyPtr robot, int bodyId) throw ()
ForwardGeometryChoreonoid (cnoid::BodyPtr robot, const std::string &bodyName) throw ()
virtual ~ForwardGeometryChoreonoid () throw ()
Protected Member Functions
void impl_compute (result_t &result, const argument_t &x) const throw ()
void impl_gradient2 (gradient_t &gradient, const argument_t &x, size_type functionId) const throw ()
Gradient computation.
virtual void impl_jacobian2 (jacobian_t &J, const argument_t &x) const throw ()
void impl_gradient (gradient_t &gradient, const argument_t &x, size_type functionId) const throw ()
template<typename Derived >
void updateDR (const typename Eigen::MatrixBase< Derived > &x) const throw ()
Detailed Description
template<typename T>
class roboptim::retargeting::ForwardGeometryChoreonoid< T >
Compute forward geometry for a particular robot model.
Robot model from choreonoid should be passed to the constructor and use for computation. The analytical jacobian must also be retrieved and returned in the impl_gradient/impl_jacobian methods.
Constructor & Destructor Documentation
template<typename T > roboptim::retargeting::ForwardGeometryChoreonoid< T >::ForwardGeometryChoreonoid (cnoid::BodyPtr robot, int bodyId) throw () [inline, explicit]
template<typename T > roboptim::retargeting::ForwardGeometryChoreonoid< T >::ForwardGeometryChoreonoid (cnoid::BodyPtr robot, const std::string & bodyName) throw () [inline, explicit]
template<typename T > virtual roboptim::retargeting::ForwardGeometryChoreonoid< T >::~ForwardGeometryChoreonoid () throw () [inline, virtual]
Member Function Documentation
template<typename T > void roboptim::retargeting::ForwardGeometryChoreonoid< T >::impl_compute (result_t & result, const argument_t & x) const throw () [inline, protected]
References transformToVector(), and roboptim::retargeting::updateRobotConfiguration().
template<typename T > void roboptim::retargeting::ForwardGeometryChoreonoid< T >::impl_gradient (gradient_t & gradient, const argument_t & x, size_type functionId) const throw () [inline, protected]
template<typename T > void roboptim::retargeting::ForwardGeometryChoreonoid< T >::impl_gradient2 (gradient_t & gradient, const argument_t & x, size_type functionId) const throw () [inline, protected]
Gradient computation.
The jacobian is as follow:
------------------------------------------------------------------ | function id || tx | ty | tz | rx | ry | rz | dof0 | ... | dofN | ------------------------------------------------------------------ | 0 (tx) || 1 | 0 | 0 | | | | 1 (ty) || 0 | 1 | 0 | [1] | Choreonoid | | 2 (tz) || 0 | 0 | 1 | | | | 3 (rx) || 0 | 0 | 0 | | | | 4 (ry) || 0 | 0 | 0 | [2] | Choreonoid | | 5 (rz) || 0 | 0 | 0 | | | ------------------------------------------------------------------
I.e. influence of configuration change on the body position.
In our case, we only compute one line of this array.
Formula [1] and [2] are available in "On the Dynamics Modeling of Free-Floating-Base Articulated Mechanisms and Applications to Humanoid Whole-Body Dynamics and Control", K. Bouyarmane, A. Kheddar.
Parameters:
gradient Gradient
x configuration (free floating then DOF values)
functionId jacobian line to be computed
References hat(), roboptim::retargeting::ForwardGeometryChoreonoid< T >::updateDR(), and roboptim::retargeting::updateRobotConfiguration().
template<typename T > virtual void roboptim::retargeting::ForwardGeometryChoreonoid< T >::impl_jacobian2 (jacobian_t & J, const argument_t & x) const throw () [inline, protected, virtual]
References hat(), roboptim::retargeting::ForwardGeometryChoreonoid< T >::updateDR(), and roboptim::retargeting::updateRobotConfiguration().
template<typename T > roboptim::retargeting::ForwardGeometryChoreonoid< T >::ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (ForwardGeometry< T >)
template<typename T > template<typename Derived > void roboptim::retargeting::ForwardGeometryChoreonoid< T >::updateDR (const typename Eigen::MatrixBase< Derived > & x) const throw () [inline, protected]
Referenced by roboptim::retargeting::ForwardGeometryChoreonoid< T >::impl_gradient2(), and roboptim::retargeting::ForwardGeometryChoreonoid< T >::impl_jacobian2().