roboptim::retargeting::problem::Joint Class Reference
roboptim::retargeting::problem::Joint Class Reference
Define the optimization problem on robot joint space.
#include <roboptim/retargeting/problem/joint.hh>
Public Types
typedef boost::shared_ptr
< roboptim::GenericDifferentiableFunction
< EigenMatrixSparse > > DifferentiableFunctionShPtr_t
typedef roboptim::Solver
< GenericDifferentiableFunction
< EigenMatrixSparse >
, boost::mpl::vector
< GenericNumericLinearFunction
< EigenMatrixSparse >
, GenericDifferentiableFunction
< EigenMatrixSparse > > > solver_t
typedef solver_t::problem_t problem_t
typedef boost::shared_ptr
< problem_t > problemShPtr_t
Public Member Functions
Joint (cnoid::MarkerMotionPtr markerMotion, cnoid::CharacterPtr character, cnoid::BodyPtr body, cnoid::MarkerIMeshPtr jointIMesh, bool enableBoneLength, bool enablePosition, bool enableCollision, bool enableTorque, bool enableZmp, const std::string &solverName, cnoid::MarkerMotionItemPtr markerMotionItem)
virtual ~Joint ()
void solve ()
Solve the underlying optimization problem.
AnimatedInteractionMeshShPtr_t animatedMesh ()
const
LaplacianDeformationEnergyShPtr_t & costLaplacian () const
LaplacianDeformationEnergyShPtr_t & costLaplacian ()
const AccelerationEnergyShPtr_t & costAcceleration () const
AccelerationEnergyShPtr_t & costAcceleration ()
const
DifferentiableFunctionShPtr_t & cost () const
DifferentiableFunctionShPtr_t & cost ()
problemShPtr_t & problem ()
const problemShPtr_t & problem () const
const GenericSolver::result_t & result () const
Return the optimization result.
TorqueShPtr_t torqueConstraint ()
void setCharacterPair (int motionIndex, cnoid::CharacterPtr org, cnoid::CharacterPtr goal)
Detailed Description
Define the optimization problem on robot joint space.
Build the optimization problem and provide a method solve () which looks for an optimal solution.
Member Typedef Documentation
typedef boost::shared_ptr< roboptim::GenericDifferentiableFunction< EigenMatrixSparse> > roboptim::retargeting::problem::Joint::DifferentiableFunctionShPtr_t
typedef solver_t::problem_t roboptim::retargeting::problem::Joint::problem_t
typedef boost::shared_ptr<problem_t> roboptim::retargeting::problem::Joint::problemShPtr_t
typedef roboptim::Solver< GenericDifferentiableFunction<EigenMatrixSparse>, boost::mpl::vector< GenericNumericLinearFunction<EigenMatrixSparse>, GenericDifferentiableFunction<EigenMatrixSparse> > > roboptim::retargeting::problem::Joint::solver_t
Constructor & Destructor Documentation
roboptim::retargeting::problem::Joint::Joint (cnoid::MarkerMotionPtr markerMotion, cnoid::CharacterPtr character, cnoid::BodyPtr body, cnoid::MarkerIMeshPtr jointIMesh, bool enableBoneLength, bool enablePosition, bool enableCollision, bool enableTorque, bool enableZmp, const std::string & solverName, cnoid::MarkerMotionItemPtr markerMotionItem) [explicit]
References roboptim::retargeting::AnimatedInteractionMesh::makeFromOptimizationVariables(), setCharacterPair(), and torqueConstraint().
roboptim::retargeting::problem::Joint::~Joint () [virtual]
Member Function Documentation
AnimatedInteractionMeshShPtr_t roboptim::retargeting::problem::Joint::animatedMesh () [inline]
const DifferentiableFunctionShPtr_t& roboptim::retargeting::problem::Joint::cost () const [inline]
DifferentiableFunctionShPtr_t& roboptim::retargeting::problem::Joint::cost () [inline]
const AccelerationEnergyShPtr_t& roboptim::retargeting::problem::Joint::costAcceleration () const [inline]
AccelerationEnergyShPtr_t& roboptim::retargeting::problem::Joint::costAcceleration () [inline]
const LaplacianDeformationEnergyShPtr_t& roboptim::retargeting::problem::Joint::costLaplacian () const [inline]
LaplacianDeformationEnergyShPtr_t& roboptim::retargeting::problem::Joint::costLaplacian () [inline]
problemShPtr_t& roboptim::retargeting::problem::Joint::problem () [inline]
const problemShPtr_t& roboptim::retargeting::problem::Joint::problem () const [inline]
const GenericSolver::result_t& roboptim::retargeting::problem::Joint::result () const [inline]
Return the optimization result.
You *have* to call solve() first otherwise the result will contain no information.
void roboptim::retargeting::problem::Joint::setCharacterPair (int motionIndex, cnoid::CharacterPtr org, cnoid::CharacterPtr goal)
References roboptim::retargeting::CharacterInfo::goal, and roboptim::retargeting::CharacterInfo::org.
Referenced by Joint().
void roboptim::retargeting::problem::Joint::solve ()
Solve the underlying optimization problem.
TorqueShPtr_t roboptim::retargeting::problem::Joint::torqueConstraint () [inline]
Referenced by Joint().