roboptim::retargeting::problem::Marker Class Reference
roboptim::retargeting::problem::Marker Class Reference
Define the optimization problem on marker (Euclidian) space.
#include <roboptim/retargeting/problem/marker.hh>
Public Types
typedef boost::shared_ptr
< roboptim::GenericDifferentiableFunction
< EigenMatrixSparse > > DifferentiableFunctionShPtr_t
typedef roboptim::Solver
< GenericDifferentiableFunction
< EigenMatrixSparse >
, boost::mpl::vector
< GenericNumericLinearFunction
< EigenMatrixSparse >
, GenericDifferentiableFunction
< EigenMatrixSparse > > > solver_t
typedef solver_t::problem_t problem_t
typedef boost::shared_ptr
< problem_t > problemShPtr_t
Public Member Functions
Marker (cnoid::MarkerMotionPtr markerMotion, cnoid::CharacterPtr character, cnoid::BodyPtr body, cnoid::MarkerIMeshPtr markerIMesh, bool enableBoneLength, bool enablePosition, bool enableCollision, bool enableTorque, bool enableZmp, const std::string &solverName, cnoid::MarkerMotionItemPtr markerMotionItem)
virtual ~Marker ()
void solve ()
Solve the underlying optimization problem.
AnimatedInteractionMeshShPtr_t animatedMesh ()
const
LaplacianDeformationEnergyShPtr_t & costLaplacian () const
LaplacianDeformationEnergyShPtr_t & costLaplacian ()
const AccelerationEnergyShPtr_t & costAcceleration () const
AccelerationEnergyShPtr_t & costAcceleration ()
const
DifferentiableFunctionShPtr_t & cost () const
DifferentiableFunctionShPtr_t & cost ()
problemShPtr_t & problem ()
const problemShPtr_t & problem () const
const GenericSolver::result_t & result () const
Return the optimization result.
TorqueShPtr_t torqueConstraint ()
void setCharacterPair (int motionIndex, cnoid::CharacterPtr org, cnoid::CharacterPtr goal)
Detailed Description
Define the optimization problem on marker (Euclidian) space.
Build the optimization problem and provide a method solve () which looks for an optimal solution.
Member Typedef Documentation
typedef boost::shared_ptr< roboptim::GenericDifferentiableFunction< EigenMatrixSparse> > roboptim::retargeting::problem::Marker::DifferentiableFunctionShPtr_t
typedef solver_t::problem_t roboptim::retargeting::problem::Marker::problem_t
typedef boost::shared_ptr<problem_t> roboptim::retargeting::problem::Marker::problemShPtr_t
typedef roboptim::Solver< GenericDifferentiableFunction<EigenMatrixSparse>, boost::mpl::vector< GenericNumericLinearFunction<EigenMatrixSparse>, GenericDifferentiableFunction<EigenMatrixSparse> > > roboptim::retargeting::problem::Marker::solver_t
Constructor & Destructor Documentation
roboptim::retargeting::problem::Marker::Marker (cnoid::MarkerMotionPtr markerMotion, cnoid::CharacterPtr character, cnoid::BodyPtr body, cnoid::MarkerIMeshPtr markerIMesh, bool enableBoneLength, bool enablePosition, bool enableCollision, bool enableTorque, bool enableZmp, const std::string & solverName, cnoid::MarkerMotionItemPtr markerMotionItem) [explicit]
References roboptim::retargeting::AnimatedInteractionMesh::makeFromOptimizationVariables(), setCharacterPair(), and torqueConstraint().
roboptim::retargeting::problem::Marker::~Marker () [virtual]
Member Function Documentation
AnimatedInteractionMeshShPtr_t roboptim::retargeting::problem::Marker::animatedMesh () [inline]
Referenced by main().
const DifferentiableFunctionShPtr_t& roboptim::retargeting::problem::Marker::cost () const [inline]
DifferentiableFunctionShPtr_t& roboptim::retargeting::problem::Marker::cost () [inline]
const AccelerationEnergyShPtr_t& roboptim::retargeting::problem::Marker::costAcceleration () const [inline]
AccelerationEnergyShPtr_t& roboptim::retargeting::problem::Marker::costAcceleration () [inline]
const LaplacianDeformationEnergyShPtr_t& roboptim::retargeting::problem::Marker::costLaplacian () const [inline]
LaplacianDeformationEnergyShPtr_t& roboptim::retargeting::problem::Marker::costLaplacian () [inline]
problemShPtr_t& roboptim::retargeting::problem::Marker::problem () [inline]
Referenced by main().
const problemShPtr_t& roboptim::retargeting::problem::Marker::problem () const [inline]
const GenericSolver::result_t& roboptim::retargeting::problem::Marker::result () const [inline]
Return the optimization result.
You *have* to call solve() first otherwise the result will contain no information.
Referenced by main().
void roboptim::retargeting::problem::Marker::setCharacterPair (int motionIndex, cnoid::CharacterPtr org, cnoid::CharacterPtr goal)
References roboptim::retargeting::CharacterInfo::goal, and roboptim::retargeting::CharacterInfo::org.
Referenced by Marker().
void roboptim::retargeting::problem::Marker::solve ()
Solve the underlying optimization problem.
Referenced by main().
TorqueShPtr_t roboptim::retargeting::problem::Marker::torqueConstraint () [inline]
Referenced by Marker().