roboptim::retargeting::ZMP< T > Class Template Reference
roboptim::retargeting::ZMP< T > Class Template Reference
Abstract class for Computing the ZMP position.
#include <roboptim/retargeting/function/zmp.hh>
Public Member Functions
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
ZMP (size_type nDofs, std::string title) throw ()
virtual ~ZMP () throw ()
template<typename Derived >
size_type configurationLength (const Eigen::MatrixBase< Derived > &x) const throw ()
template<typename Derived >
Eigen::VectorBlock< const Derived > translation (const Eigen::MatrixBase< Derived > &x) const throw ()
template<typename Derived >
Eigen::VectorBlock< Derived > translation (Eigen::MatrixBase< Derived > &x) const throw ()
template<typename Derived >
Eigen::VectorBlock< const Derived > rotation (const Eigen::MatrixBase< Derived > &x) const throw ()
template<typename Derived >
Eigen::VectorBlock< Derived > rotation (Eigen::MatrixBase< Derived > &x) const throw ()
template<typename Derived >
Eigen::VectorBlock< const Derived > q (const Eigen::MatrixBase< Derived > &x, bool withBaseLink=true) const throw ()
template<typename Derived >
Eigen::VectorBlock< Derived > q (Eigen::MatrixBase< Derived > &x, bool withBaseLink=true) const throw ()
template<typename Derived >
Eigen::VectorBlock< const Derived > dq (const Eigen::MatrixBase< Derived > &x, bool withBaseLink=true) const throw ()
template<typename Derived >
Eigen::VectorBlock< Derived > dq (Eigen::MatrixBase< Derived > &x, bool withBaseLink=true) const throw ()
template<typename Derived >
Eigen::VectorBlock< const Derived > ddq (const Eigen::MatrixBase< Derived > &x, bool withBaseLink=true) const throw ()
template<typename Derived >
Eigen::VectorBlock< Derived > ddq (Eigen::MatrixBase< Derived > &x, bool withBaseLink=true) const throw ()
Detailed Description
template<typename T>
class roboptim::retargeting::ZMP< T >
Abstract class for Computing the ZMP position.
Input:
...where q is [x, y, z, alpha, beta, gamma, q0, qN]
(x, y, z) is the base position (alpha, beta, gamma) is base attitude using angle axis representation (q0, ..., qN) are the joints values
Output:
Implementation must be done in zmp/*.hh depending on how the computation is done (metapod, choreonoid or linear model)
Template Parameters:
T Function traits type
Constructor & Destructor Documentation
template<typename T > roboptim::retargeting::ZMP< T >::ZMP (size_type nDofs, std::string title) throw () [inline, explicit]
template<typename T > virtual roboptim::retargeting::ZMP< T >::~ZMP () throw () [inline, virtual]
Member Function Documentation
template<typename T > template<typename Derived > size_type roboptim::retargeting::ZMP< T >::configurationLength (const Eigen::MatrixBase< Derived > & x) const throw () [inline]
Referenced by roboptim::retargeting::ZMP< T >::ddq(), roboptim::retargeting::ZMP< T >::dq(), and roboptim::retargeting::ZMP< T >::q().
template<typename T > template<typename Derived > Eigen::VectorBlock<const Derived> roboptim::retargeting::ZMP< T >::ddq (const Eigen::MatrixBase< Derived > & x, bool withBaseLink = true) const throw () [inline]
References roboptim::retargeting::ZMP< T >::configurationLength().
Referenced by roboptim::retargeting::ZMPChoreonoid< T >::fillStates(), and roboptim::retargeting::ZMPMetapod< T, R >::impl_compute().
template<typename T > template<typename Derived > Eigen::VectorBlock<Derived> roboptim::retargeting::ZMP< T >::ddq (Eigen::MatrixBase< Derived > & x, bool withBaseLink = true) const throw () [inline]
References roboptim::retargeting::ZMP< T >::configurationLength().
template<typename T > template<typename Derived > Eigen::VectorBlock<const Derived> roboptim::retargeting::ZMP< T >::dq (const Eigen::MatrixBase< Derived > & x, bool withBaseLink = true) const throw () [inline]
References roboptim::retargeting::ZMP< T >::configurationLength().
Referenced by roboptim::retargeting::ZMPChoreonoid< T >::fillStates(), and roboptim::retargeting::ZMPMetapod< T, R >::impl_compute().
template<typename T > template<typename Derived > Eigen::VectorBlock<Derived> roboptim::retargeting::ZMP< T >::dq (Eigen::MatrixBase< Derived > & x, bool withBaseLink = true) const throw () [inline]
References roboptim::retargeting::ZMP< T >::configurationLength().
template<typename T > template<typename Derived > Eigen::VectorBlock<const Derived> roboptim::retargeting::ZMP< T >::q (const Eigen::MatrixBase< Derived > & x, bool withBaseLink = true) const throw () [inline]
References roboptim::retargeting::ZMP< T >::configurationLength().
Referenced by roboptim::retargeting::ZMPChoreonoid< T >::fillStates(), and roboptim::retargeting::ZMPMetapod< T, R >::impl_compute().
template<typename T > template<typename Derived > Eigen::VectorBlock<Derived> roboptim::retargeting::ZMP< T >::q (Eigen::MatrixBase< Derived > & x, bool withBaseLink = true) const throw () [inline]
References roboptim::retargeting::ZMP< T >::configurationLength().
template<typename T > roboptim::retargeting::ZMP< T >::ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
template<typename T > template<typename Derived > Eigen::VectorBlock<const Derived> roboptim::retargeting::ZMP< T >::rotation (const Eigen::MatrixBase< Derived > & x) const throw () [inline]
template<typename T > template<typename Derived > Eigen::VectorBlock<Derived> roboptim::retargeting::ZMP< T >::rotation (Eigen::MatrixBase< Derived > & x) const throw () [inline]
template<typename T > template<typename Derived > Eigen::VectorBlock<const Derived> roboptim::retargeting::ZMP< T >::translation (const Eigen::MatrixBase< Derived > & x) const throw () [inline]
template<typename T > template<typename Derived > Eigen::VectorBlock<Derived> roboptim::retargeting::ZMP< T >::translation (Eigen::MatrixBase< Derived > & x) const throw () [inline]