roboptim::retargeting::Torque< T > Class Template Reference
roboptim::retargeting::Torque< T > Class Template Reference
Compute the Torque of each joint.
#include <roboptim/retargeting/function/torque.hh>
Public Member Functions
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
Torque (size_type nDofs, std::string title) throw ()
virtual ~Torque () throw ()
template<typename Derived >
size_type configurationLength (const Eigen::MatrixBase< Derived > &x) const throw ()
template<typename Derived >
Eigen::VectorBlock< const Derived > translation (const Eigen::MatrixBase< Derived > &x) const throw ()
template<typename Derived >
Eigen::VectorBlock< Derived > translation (Eigen::MatrixBase< Derived > &x) const throw ()
template<typename Derived >
Eigen::VectorBlock< const Derived > rotation (const Eigen::MatrixBase< Derived > &x) const throw ()
template<typename Derived >
Eigen::VectorBlock< Derived > rotation (Eigen::MatrixBase< Derived > &x) const throw ()
template<typename Derived >
Eigen::VectorBlock< const Derived > q (const Eigen::MatrixBase< Derived > &x, bool withBaseLink=true) const throw ()
template<typename Derived >
Eigen::VectorBlock< Derived > q (Eigen::MatrixBase< Derived > &x, bool withBaseLink=true) const throw ()
template<typename Derived >
Eigen::VectorBlock< const Derived > dq (const Eigen::MatrixBase< Derived > &x, bool withBaseLink=true) const throw ()
template<typename Derived >
Eigen::VectorBlock< Derived > dq (Eigen::MatrixBase< Derived > &x, bool withBaseLink=true) const throw ()
template<typename Derived >
Eigen::VectorBlock< const Derived > ddq (const Eigen::MatrixBase< Derived > &x, bool withBaseLink=true) const throw ()
template<typename Derived >
Eigen::VectorBlock< Derived > ddq (Eigen::MatrixBase< Derived > &x, bool withBaseLink=true) const throw ()
Detailed Description
template<typename T>
class roboptim::retargeting::Torque< T >
Compute the Torque of each joint.
Input:
...where q is [x, y, z, alpha, beta, gamma, q0, qN]
(x, y, z) is the base position (alpha, beta, gamma) is base attitude using angle axis representation (q0, ..., qN) are the joints values
Output:
Template Parameters:
T Function traits type
Constructor & Destructor Documentation
template<typename T > roboptim::retargeting::Torque< T >::Torque (size_type nDofs, std::string title) throw () [inline, explicit]
template<typename T > virtual roboptim::retargeting::Torque< T >::~Torque () throw () [inline, virtual]
Member Function Documentation
template<typename T > template<typename Derived > size_type roboptim::retargeting::Torque< T >::configurationLength (const Eigen::MatrixBase< Derived > & x) const throw () [inline]
Referenced by roboptim::retargeting::Torque< T >::ddq(), roboptim::retargeting::Torque< T >::dq(), and roboptim::retargeting::Torque< T >::q().
template<typename T > template<typename Derived > Eigen::VectorBlock<const Derived> roboptim::retargeting::Torque< T >::ddq (const Eigen::MatrixBase< Derived > & x, bool withBaseLink = true) const throw () [inline]
References roboptim::retargeting::Torque< T >::configurationLength().
Referenced by roboptim::retargeting::TorqueChoreonoid< T >::impl_compute(), and roboptim::retargeting::TorqueMetapod< T, R >::impl_compute().
template<typename T > template<typename Derived > Eigen::VectorBlock<Derived> roboptim::retargeting::Torque< T >::ddq (Eigen::MatrixBase< Derived > & x, bool withBaseLink = true) const throw () [inline]
References roboptim::retargeting::Torque< T >::configurationLength().
template<typename T > template<typename Derived > Eigen::VectorBlock<const Derived> roboptim::retargeting::Torque< T >::dq (const Eigen::MatrixBase< Derived > & x, bool withBaseLink = true) const throw () [inline]
References roboptim::retargeting::Torque< T >::configurationLength().
Referenced by roboptim::retargeting::TorqueChoreonoid< T >::impl_compute(), and roboptim::retargeting::TorqueMetapod< T, R >::impl_compute().
template<typename T > template<typename Derived > Eigen::VectorBlock<Derived> roboptim::retargeting::Torque< T >::dq (Eigen::MatrixBase< Derived > & x, bool withBaseLink = true) const throw () [inline]
References roboptim::retargeting::Torque< T >::configurationLength().
template<typename T > template<typename Derived > Eigen::VectorBlock<const Derived> roboptim::retargeting::Torque< T >::q (const Eigen::MatrixBase< Derived > & x, bool withBaseLink = true) const throw () [inline]
References roboptim::retargeting::Torque< T >::configurationLength().
Referenced by roboptim::retargeting::TorqueChoreonoid< T >::impl_compute(), and roboptim::retargeting::TorqueMetapod< T, R >::impl_compute().
template<typename T > template<typename Derived > Eigen::VectorBlock<Derived> roboptim::retargeting::Torque< T >::q (Eigen::MatrixBase< Derived > & x, bool withBaseLink = true) const throw () [inline]
References roboptim::retargeting::Torque< T >::configurationLength().
template<typename T > roboptim::retargeting::Torque< T >::ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
template<typename T > template<typename Derived > Eigen::VectorBlock<const Derived> roboptim::retargeting::Torque< T >::rotation (const Eigen::MatrixBase< Derived > & x) const throw () [inline]
template<typename T > template<typename Derived > Eigen::VectorBlock<Derived> roboptim::retargeting::Torque< T >::rotation (Eigen::MatrixBase< Derived > & x) const throw () [inline]
template<typename T > template<typename Derived > Eigen::VectorBlock<const Derived> roboptim::retargeting::Torque< T >::translation (const Eigen::MatrixBase< Derived > & x) const throw () [inline]
template<typename T > template<typename Derived > Eigen::VectorBlock<Derived> roboptim::retargeting::Torque< T >::translation (Eigen::MatrixBase< Derived > & x) const throw () [inline]