roboptim::retargeting::MarkerToJointFunctionFactory Class Reference
roboptim::retargeting::MarkerToJointFunctionFactory Class Reference
Creates functions from their name for joint-joint optimization.
#include <roboptim/retargeting/problem/marker-to-joint-function-factory.hh>
Public Member Functions
template<typename T >
boost::shared_ptr< T > buildFunction (const std::string &name)
Instantiate a function from its name.
template<typename T >
Constraint< T > buildConstraint (const std::string &name)
Instantiate a constraint from its name.
MarkerToJointFunctionFactory (const MarkerToJointFunctionData &data)
Constructor and Destructor.
~MarkerToJointFunctionFactory ()
Static Public Member Functions
static std::vector< std::string > listFunctions ()
List supported functions.
Detailed Description
Creates functions from their name for joint-joint optimization.
Constructor & Destructor Documentation
roboptim::retargeting::MarkerToJointFunctionFactory::MarkerToJointFunctionFactory (const MarkerToJointFunctionData & data) [explicit]
Constructor and Destructor.
Constructor
Parameters:
data problem data (trajectories, etc.)
roboptim::retargeting::MarkerToJointFunctionFactory::~MarkerToJointFunctionFactory ()
Member Function Documentation
template<typename T > Constraint< T > roboptim::retargeting::MarkerToJointFunctionFactory::buildConstraint (const std::string & name)
Instantiate a constraint from its name.
This method creates a constraint object from the constraint name.
Parameters:
[in] name function name
Returns:
newly created constraint object
Template Parameters:
T function type (e.g. DifferentiableFunction)
References roboptim::retargeting::MarkerToJointFunctionData::disabledJointsConfiguration, roboptim::retargeting::Constraint< T >::function, roboptim::retargeting::Constraint< T >::intervals, roboptim::retargeting::MarkerToJointFunctionData::nDofsFull(), roboptim::retargeting::MarkerToJointFunctionData::robotModel, roboptim::retargeting::Constraint< T >::scales, roboptim::retargeting::Constraint< T >::stateFunctionOrder, and roboptim::retargeting::Constraint< T >::type.
Referenced by roboptim::retargeting::MarkerToJointProblemBuilder< T >::operator()().
template<typename T > boost::shared_ptr< T > roboptim::retargeting::MarkerToJointFunctionFactory::buildFunction (const std::string & name)
Instantiate a function from its name.
This method creates a function (cost or constraint) from its name.
Parameters:
[in] name function name
Returns:
shared pointer to the newly created function
Template Parameters:
T function type (e.g. DifferentiableFunction)
References roboptim::retargeting::detail::MarkerToJointFunctionFactoryMapping< T >::Mapping::factory, and roboptim::retargeting::detail::MarkerToJointFunctionFactoryMapping< T >::Mapping::name.
Referenced by roboptim::retargeting::MarkerToJointProblemBuilder< T >::operator()().
std::vector< std::string > roboptim::retargeting::MarkerToJointFunctionFactory::listFunctions () [inline, static]
List supported functions.
Each element of this string can be passed to buildFunction method to create the corresponding function.
References roboptim::retargeting::detail::MarkerToJointFunctionFactoryMapping< T >::Mapping::name.