roboptim::retargeting Namespace Reference
roboptim::retargeting Namespace Reference
Namespaces
namespace problem
Classes
class AccelerationEnergy
Compute acceleration based term that smooths result trajectory.
struct Vertex
Robot body (vertex of the main graph)
struct Edge
Robot segment/link (edge of the the main graph)
struct InteractionMeshVertex
struct InteractionMeshEdge
class AnimatedInteractionMesh
Stores a set of interaction mesh representing a motion.
class GraphEdgeWriter
Write an edge using the Graphviz format.
class GraphVertexWriter
Write a vertex using the Graphviz format.
class InteractionMeshGraphEdgeWriter
Write an edge using the Graphviz format.
class InteractionMeshGraphVertexWriter
Write a vertex using the Graphviz format.
class BoneLength
Bone length constraint.
struct Bone
Index1 should be smaller than index2 to sequentially insert the coefficients of the bone length constraints into the sparse matrix.
struct CharacterInfo
class Collision
Collision constraint (not implemented).
class CostReferenceTrajectory
class ForwardGeometryChoreonoid
Compute forward geometry for a particular robot model.
class ForwardGeometry
Compute a particular body position for a given configuration.
class JointToMarkerPosition
Compute the offset between one joint and one or more attached markers.
class LaplacianDeformationEnergy
Laplacian Deformation Energy.
class MinimumJerkTrajectory
Minimum jerk trajectory computation.
class TorqueChoreonoid
Torque position computed through Choreonoid.
class TorqueMetapod
Torque position computed through Metapod.
class ZMPInvertedPendulum
ZMP position computed using the Inverted Pendulum model.
class ZMPMetapod
ZMP position computed through Metapod.
class LaplacianCoordinate
Laplacian Coordinates.
class Position
Position constraint (not implemented)
class Torque
Torque constraints (not yet implemented)
class ZMP
ZMP constraints (not yet implemented)
class MinimumJerkOptimizationLogger
Typedefs
typedef boost::shared_ptr
< AccelerationEnergy > AccelerationEnergyShPtr_t
typedef boost::shared_ptr
< AnimatedInteractionMesh > AnimatedInteractionMeshShPtr_t
typedef boost::shared_ptr
< BoneLength > BoneLengthShPtr_t
typedef boost::shared_ptr
< Collision > CollisionShPtr_t
typedef boost::shared_ptr
< LaplacianCoordinate > LaplacianCoordinateShPtr_t
typedef boost::shared_ptr
< LaplacianDeformationEnergy > LaplacianDeformationEnergyShPtr_t
typedef boost::shared_ptr
< Position > PositionShPtr_t
typedef boost::shared_ptr< Torque > TorqueShPtr_t
typedef boost::shared_ptr< ZMP > ZmpShPtr_t
Functions
template<typename T >
boost::shared_ptr
< GenericDifferentiableFunction
< T > > acceleration ()
Compute acceleration from position.
template<typename T >
void plotQ (const T &state)
void plotQTorque (const std::vector< Torque::robot_t::confVector > &q, const std::vector< Torque::robot_t::confVector > &dq, const std::vector< Torque::robot_t::confVector > &ddq)
std::string yamlNodeTypeToString (const YAML::NodeType::value &nodeType)
std::string unexpectedNodeTypeErrorMessage (const YAML::NodeType::value &nodeType, const YAML::NodeType::value &expectedNodeType)
void checkNodeType (const YAML::Node &node, const YAML::NodeType::value &expectedType)
void plotQ (const std::vector< ZMP::robot_t::confVector > &q, const std::vector< ZMP::robot_t::confVector > &dq, const std::vector< ZMP::robot_t::confVector > &ddq)
Typedef Documentation
typedef boost::shared_ptr<AccelerationEnergy> roboptim::retargeting::AccelerationEnergyShPtr_t
typedef boost::shared_ptr<AnimatedInteractionMesh> roboptim::retargeting::AnimatedInteractionMeshShPtr_t
typedef boost::shared_ptr<BoneLength> roboptim::retargeting::BoneLengthShPtr_t
typedef boost::shared_ptr<Collision> roboptim::retargeting::CollisionShPtr_t
typedef boost::shared_ptr<LaplacianCoordinate> roboptim::retargeting::LaplacianCoordinateShPtr_t
typedef boost::shared_ptr<LaplacianDeformationEnergy> roboptim::retargeting::LaplacianDeformationEnergyShPtr_t
typedef boost::shared_ptr<Position> roboptim::retargeting::PositionShPtr_t
typedef boost::shared_ptr<Torque> roboptim::retargeting::TorqueShPtr_t
typedef boost::shared_ptr<ZMP> roboptim::retargeting::ZmpShPtr_t
Function Documentation
template<typename T > boost::shared_ptr<GenericDifferentiableFunction<T> > roboptim::retargeting::acceleration ()
Compute acceleration from position.
Use second derivative as acceleration.
VectorInterpolation should be used here for implementation.
void roboptim::retargeting::checkNodeType (const YAML::Node & node, const YAML::NodeType::value & expectedType)
References unexpectedNodeTypeErrorMessage().
Referenced by roboptim::retargeting::AnimatedInteractionMesh::loadAnimatedMesh().
template<typename T > void roboptim::retargeting::plotQ (const T & state)
void roboptim::retargeting::plotQ (const std::vector< ZMP::robot_t::confVector > & q, const std::vector< ZMP::robot_t::confVector > & dq, const std::vector< ZMP::robot_t::confVector > & ddq)
void roboptim::retargeting::plotQTorque (const std::vector< Torque::robot_t::confVector > & q, const std::vector< Torque::robot_t::confVector > & dq, const std::vector< Torque::robot_t::confVector > & ddq)
std::string roboptim::retargeting::unexpectedNodeTypeErrorMessage (const YAML::NodeType::value & nodeType, const YAML::NodeType::value & expectedNodeType)
References yamlNodeTypeToString().
Referenced by checkNodeType().
std::string roboptim::retargeting::yamlNodeTypeToString (const YAML::NodeType::value & nodeType)
Referenced by unexpectedNodeTypeErrorMessage().