roboptim-retarget-motion.cc File Reference
roboptim-retarget-motion.cc File Reference
#include <iostream>
#include <string>
#include <boost/format.hpp>
#include <boost/graph/graphviz.hpp>
#include <boost/program_options.hpp>
#include <log4cxx/logger.h>
#include <log4cxx/xml/domconfigurator.h>
#include <roboptim/core/visualization/gnuplot.hh>
#include <roboptim/retargeting/problem/marker.hh>
#include <roboptim/retargeting/config.hh>
#include <cnoid/BodyLoader>
#include "directories.hh"
Functions
void help (const boost::program_options::options_description &desc)
void version ()
int main (int argc, char **argv)
Function Documentation
void help (const boost::program_options::options_description & desc)
Referenced by main().
int main (int argc, char ** argv)
NDEBUG
References roboptim::retargeting::problem::Marker::animatedMesh(), help(), roboptim::retargeting::problem::Marker::problem(), roboptim::retargeting::problem::Marker::result(), roboptim::retargeting::problem::Marker::solve(), and version().
void version ()
Referenced by main().